name: "firestore-mgr: Unit Tests"

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'firestore-mgr/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'firestore-mgr/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: firestore-mgr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up Python 3.10
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -q --upgrade pip
          pip install -r requirements.txt
          echo "GCP_PROJECT=square-webhook-123456" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          pip install -q flake8 pytest pytest-cov
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
