name: "firestore-mgr: Deploy to GCP"

on:
  push:
    branches:
      - main
    paths:
      - 'firestore-mgr/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: firestore-mgr

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up auth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v1.0.0
        with:
          workload_identity_provider: projects/194415472833/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@serverless-fish-fry.iam.gserviceaccount.com
          create_credentials_file: 'true'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587 # v1.1.0
        with:
          project_id: serverless-fish-fry

      - name: "Export environment variables to yaml file"
        env:
          SQUARE_ENVIRONMENT: production
          EVENT_DATE: "2023-04-29"
        run: |
          echo "SQUARE_ACCESS_TOKEN: \"${{ secrets.SQUARE_ACCESS_TOKEN }}\"" > .env.yaml
          echo "SQUARE_ENVIRONMENT: \"${SQUARE_ENVIRONMENT}\"" >> .env.yaml
          echo "SQUARE_LOCATION: \"${{ secrets.SQUARE_LOCATION }}\"" >> .env.yaml
          echo "EVENT_DATE: \"${EVENT_DATE}\"" >> .env.yaml

      - name: "Deploy firestore-mgr-created function with a Firestore trigger"
        run: |
          gcloud functions deploy firestore-mgr-created --region us-east1 \
          --entry-point handle_created --env-vars-file .env.yaml \
          --runtime python311 --memory=256MB \
          --trigger-event "providers/cloud.firestore/eventTypes/document.create" \
          --trigger-resource "projects/serverless-fish-fry/databases/(default)/documents/events/2023-04-29/orders/{order}"

      - name: "Deploy firestore-mgr-updated function with a Firestore trigger"
        run: |
          gcloud functions deploy firestore-mgr-updated --region us-east1 \
          --entry-point handle_updated --env-vars-file .env.yaml \
          --runtime python311 --memory=256MB \
          --trigger-event "providers/cloud.firestore/eventTypes/document.update" \
          --trigger-resource "projects/serverless-fish-fry/databases/(default)/documents/events/2023-04-29/orders/{order}"
