name: "sql-mgr: Deploy to GCP"

on:
  push:
    branches:
      - main
    paths:
      - 'sql-mgr/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: sql-mgr

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up auth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v1.0.0
        with:
          workload_identity_provider: projects/194415472833/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-actions@serverless-fish-fry.iam.gserviceaccount.com
          create_credentials_file: 'true'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587 # v1.1.0
        with:
          project_id: serverless-fish-fry

      - name: "Export environment variables to yaml file"
        env:
          GCS_BUCKET: kofc7186-fishfry
          EVENT_DATE: "2023-04-29"
        run: |
          echo "GCS_BUCKET: \"${GCS_BUCKET}\"" > .env.yaml
          echo "EVENT_DATE: \"${EVENT_DATE}\"" >> .env.yaml

      - name: "Deploy print function with a HTTP trigger"
        run: |
          gcloud functions deploy print --region us-east1 --entry-point handle_print \
          --env-vars-file .env.yaml --runtime python311 --memory=128MB --trigger-http \
          --allow-unauthenticated
