name: "sql-mgr: Unit Tests"

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'sql-mgr/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'sql-mgr/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: sql-mgr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Set up Python 3.10
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4.3.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -q --upgrade pip
          pip install -r requirements.txt
          echo "GCP_PROJECT=square-webhook-123456" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          pip install -q flake8 pytest pytest-cov
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
